### ISSUE TITLE
Missing token in `brew info buildkite-agent`

### ISSUE THREAD

**Issue by keithpitt** [buildkite/homebrew-buildkite#1]
When running `brew info buildkite-agent`, the example you are given to run is missing the token:

```
Or, if you don't want/need launchctl, you can just run:
    buildkite-agent start \
      --bootstrap-script /usr/local/share/buildkite-agent/bootstrap.sh \
      --build-path /usr/local/var/buildkite-agent/builds \
      --hooks-path /usr/local/etc/buildkite-agent/hooks \
      --token  \
      --meta-data mac=true
```

Perhaps if no token is present, we replace it with `[token]` or something?

**Comment by keithpitt** [comment]
Or, I suppose reading the plist if one is present, and dumping the token in there may be bad? Cause that'd be kinda handy...

**Comment by toolmantim** [comment]
Ah, that's because I ask for `--token` to be an option to the formula. It was a hack. We need to move away from worrying about passing in any parameters to the formula, or agent, and instead just have a config file.

**Comment by toolmantim** [comment]
Fixed now
