### ISSUE TITLE
Brew install not working as documented

### ISSUE THREAD

**Issue by moosecanswim** [buildkite/homebrew-buildkite#28]
Im on an m1 mac and tried to run the command on the buildkite docs.

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/21246992/209159250-4221dcae-dd7e-44c2-88e5-c6dc07a05cb2.png">

**Comment by DrJosh9000** [comment]
Hi @moosecanswim ! Thanks for reporting the issue. 
Though I can't seem to replicate it on my own M1 MacBook:
<img width="649" alt="Screenshot 2023-01-17 at 5 41 46 pm" src="https://user-images.githubusercontent.com/2398124/212827662-070021eb-c509-445d-8170-bb0e2bfdaaf1.png">

Are you able to `brew tap` other Taps?

It could be a problem with your local SSH config (here's one person's experience: https://blog.muya.co.ke/homebrew-installation-error/) or possibly with GitHub itself (https://stackoverflow.com/questions/74370326/why-is-git-giving-me-fatal-remote-error-is-not-a-valid-repository-name-when).

**Comment by sj26** [comment]
Hi @moosecanswim, we're going to close this but please reopen if you're still having issues.
