### ISSUE TITLE
Error: undefined method `gsub' for #<Formulary::FormulaNamespace...

### ISSUE THREAD

**Issue by PiotrTrzpil** [buildkite/homebrew-buildkite#7]
Hi, when installing the agent using:

`brew install --token='...my token...' buildkite-agent`

The result is:

```
Error: undefined method `gsub' for #<Formulary::FormulaNamespace8b233f8ed1fcdae9ad16a04104650bb0::BuildkiteAgent:0x007fa719a6d200>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:100:in `default_config_file'
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:82:in `install'
```

Seems like it might be related to the latest change?

**Comment by keithpitt** [comment]
Hey @PiotrTrzpil, I just tried to reproduce this locally and the agent installs just fine.

```

**Comment by keithpitt** [comment]
Oh! Sorry, I didn't have enough ☕️ this morning. This problem should be fixed now thanks to https://github.com/buildkite/homebrew-buildkite/commit/a9946b75fc254f84cc8e163765af9e0e610133ec
